<a href="https://colab.research.google.com/github/Khalidaman9555/IDS-AI/blob/main/Training.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import os

# Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

# Define dataset path from Google Drive
dataset_path = '/content/drive/MyDrive/Colab Notebooks/datasets/ML-EdgeIIoT-dataset.csv'

# Verify file exists
if os.path.exists(dataset_path):
    print(f"Dataset found at: {dataset_path}")
    # Load dataset
    try:
        df = pd.read_csv(dataset_path)
        print(f"Dataset loaded successfully. Shape: {df.shape}")
        print("\nFirst 5 rows:")
        print(df.head())
    except Exception as e:
        print(f"Error loading dataset: {e}")
else:
    print(f"Error: Dataset not found at {dataset_path}. Please check the path.")

Mounted at /content/drive
Dataset found at: /content/drive/MyDrive/Colab Notebooks/datasets/ML-EdgeIIoT-dataset.csv


<ipython-input-2-79163c29cf59>:16: DtypeWarning: Columns (3,6,11,13,14,15,16,17,31,32,34,39,45,51,54,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(dataset_path)


Dataset loaded successfully. Shape: (157800, 63)

First 5 rows:
  frame.time    ip.src_host ip.dst_host arp.dst.proto_ipv4  arp.opcode  \
0        6.0  192.168.0.152         0.0                0.0         0.0   
1        6.0  192.168.0.101         0.0                0.0         0.0   
2        6.0  192.168.0.152         0.0                0.0         0.0   
3        6.0  192.168.0.101         0.0                0.0         0.0   
4        6.0  192.168.0.152         0.0                0.0         0.0   

   arp.hw.size arp.src.proto_ipv4  icmp.checksum  icmp.seq_le  \
0          0.0                0.0            0.0          0.0   
1          0.0                0.0            0.0          0.0   
2          0.0                0.0            0.0          0.0   
3          0.0                0.0            0.0          0.0   
4          0.0                0.0            0.0          0.0   

   icmp.transmit_timestamp  ...  mqtt.proto_len mqtt.protoname  mqtt.topic  \
0                     

In [ ]:
import pandas as pd
import os

# Mount Google Drive
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

# Define dataset path
dataset_path = '/content/drive/MyDrive/Colab Notebooks/datasets/ML-EdgeIIoT-dataset.csv'

# Verify file exists
if os.path.exists(dataset_path):
    print(f"Dataset found at: {dataset_path}")
    # Load dataset with low_memory=False
    try:
        df = pd.read_csv(dataset_path, low_memory=False)
        print(f"Dataset loaded successfully. Shape: {df.shape}")
        print("\nFirst 5 rows:")
        print(df.head())
    except Exception as e:
        print(f"Error loading dataset: {e}")
else:
    print(f"Error: Dataset not found at {dataset_path}. Please check the path.")

Mounted at /content/drive
Dataset found at: /content/drive/MyDrive/Colab Notebooks/datasets/ML-EdgeIIoT-dataset.csv
Dataset loaded successfully. Shape: (157800, 63)

First 5 rows:
  frame.time    ip.src_host ip.dst_host arp.dst.proto_ipv4  arp.opcode  \
0        6.0  192.168.0.152         0.0                0.0         0.0   
1        6.0  192.168.0.101         0.0                0.0         0.0   
2        6.0  192.168.0.152         0.0                0.0         0.0   
3        6.0  192.168.0.101         0.0                0.0         0.0   
4        6.0  192.168.0.152         0.0                0.0         0.0   

   arp.hw.size arp.src.proto_ipv4  icmp.checksum  icmp.seq_le  \
0          0.0                0.0            0.0          0.0   
1          0.0                0.0            0.0          0.0   
2          0.0                0.0            0.0          0.0   
3          0.0                0.0            0.0          0.0   
4          0.0                0.0            0.0  

In [ ]:
import pandas as pd
import os

# Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

# Define dataset path from Google Drive
dataset_path = '/content/drive/MyDrive/Colab Notebooks/datasets/ML-EdgeIIoT-dataset.csv'

# Verify file exists
if os.path.exists(dataset_path):
    print(f"Dataset found at: {dataset_path}")
    # Load dataset with low_memory=False
    try:
        df = pd.read_csv(dataset_path, low_memory=False)
        print(f"Dataset loaded successfully. Shape: {df.shape}")
        print("\nFirst 5 rows:")
        print(df.head())
    except Exception as e:
        print(f"Error loading dataset: {e}")
else:
    print(f"Error: Dataset not found at {dataset_path}. Please check the path.")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Dataset found at: /content/drive/MyDrive/Colab Notebooks/datasets/ML-EdgeIIoT-dataset.csv
Dataset loaded successfully. Shape: (157800, 63)

First 5 rows:
  frame.time    ip.src_host ip.dst_host arp.dst.proto_ipv4  arp.opcode  \
0        6.0  192.168.0.152         0.0                0.0         0.0   
1        6.0  192.168.0.101         0.0                0.0         0.0   
2        6.0  192.168.0.152         0.0                0.0         0.0   
3        6.0  192.168.0.101         0.0                0.0         0.0   
4        6.0  192.168.0.152         0.0                0.0         0.0   

   arp.hw.size arp.src.proto_ipv4  icmp.checksum  icmp.seq_le  \
0          0.0                0.0            0.0          0.0   
1          0.0                0.0            0.0          0.0   
2          0.0                0.0            0.0          0.0   
3          0

In [ ]:
# Identify categorical features
print("\nDataset Info:")
print(df.info())

# Select categorical features (object type or low-cardinality integers)
categorical_features = df.select_dtypes(include=['object', 'category']).columns.tolist()

# Check numeric features for low-cardinality (potential categorical)
numeric_features = df.select_dtypes(include=['int64', 'float64']).columns.tolist()
for col in numeric_features:
    unique_count = df[col].nunique()
    if unique_count < 20:  # Threshold for categorical-like numeric features
        categorical_features.append(col)
        print(f"{col} has {unique_count} unique values, likely categorical.")

# Remove target columns from categorical features
target_columns = ['Attack_label', 'Attack_type']
categorical_features = [col for col in categorical_features if col not in target_columns]

print("\nIdentified Categorical Features (Excluding Targets):")
print(categorical_features)

# Assess cardinality for encoding decisions
print("\nCardinality of Categorical Features:")
for col in categorical_features:
    unique_count = df[col].nunique()
    print(f"{col}: {unique_count} unique values")


Dataset Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 157800 entries, 0 to 157799
Data columns (total 63 columns):
 #   Column                     Non-Null Count   Dtype  
---  ------                     --------------   -----  
 0   frame.time                 157800 non-null  object 
 1   ip.src_host                157800 non-null  object 
 2   ip.dst_host                157800 non-null  object 
 3   arp.dst.proto_ipv4         157800 non-null  object 
 4   arp.opcode                 157800 non-null  float64
 5   arp.hw.size                157800 non-null  float64
 6   arp.src.proto_ipv4         157800 non-null  object 
 7   icmp.checksum              157800 non-null  float64
 8   icmp.seq_le                157800 non-null  float64
 9   icmp.transmit_timestamp    157800 non-null  float64
 10  icmp.unused                157800 non-null  float64
 11  http.file_data             157800 non-null  object 
 12  http.content_length        157800 non-null  float64
 13  http.request.u

In [ ]:
!pip install category_encoders

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 85.7/85.7 kB 2.3 MB/s eta 0:00:00


In [ ]:
from sklearn.preprocessing import OneHotEncoder
from category_encoders import TargetEncoder
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np

# Install category_encoders if not installed
!pip install category_encoders

# Define features
low_cardinality = [
    'arp.dst.proto_ipv4', 'arp.src.proto_ipv4', 'http.request.method', 'http.referer',
    'http.request.version', 'dns.qry.name.len', 'mqtt.conack.flags', 'mqtt.protoname',
    'mqtt.topic', 'arp.opcode', 'arp.hw.size', 'http.response', 'tcp.connection.fin',
    'tcp.connection.rst', 'tcp.connection.syn', 'tcp.connection.synack', 'tcp.flags',
    'tcp.flags.ack', 'dns.retransmission', 'dns.retransmit_request', 'mqtt.conflag.cleansess',
    'mqtt.conflags', 'mqtt.hdrflags', 'mqtt.len', 'mqtt.msgtype', 'mqtt.proto_len',
    'mqtt.topic_len', 'mqtt.ver'
]
high_cardinality = [
    'frame.time', 'ip.src_host', 'ip.dst_host', 'http.file_data', 'http.request.uri.query',
    'http.request.full_uri', 'tcp.options', 'tcp.payload', 'tcp.srcport', 'mqtt.msg'
]
exclude_features = [
    'icmp.unused', 'http.tls_port', 'dns.qry.type', 'dns.retransmit_request_in',
    'mbtcp.len', 'mbtcp.trans_id', 'mbtcp.unit_id'
]

# Define features and target
target_col = 'Attack_label'
X = df.drop(columns=[target_col, 'Attack_type'] + exclude_features)
y = df[target_col]

# Convert low-cardinality features to string
for col in low_cardinality:
    X[col] = X[col].astype(str)

# Split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# One-hot encoding
try:
    one_hot_encoder = OneHotEncoder(sparse=False, handle_unknown='ignore')
    if low_cardinality:
        one_hot_encoded = one_hot_encoder.fit_transform(X_train[low_cardinality])
        print(f"One-hot encoded shape: {one_hot_encoded.shape}")
        one_hot_columns = one_hot_encoder.get_feature_names_out(low_cardinality)
        one_hot_df = pd.DataFrame(one_hot_encoded, columns=one_hot_columns, index=X_train.index)
        X_train = pd.concat([X_train.drop(columns=low_cardinality), one_hot_df], axis=1)

        # Apply to test data
        one_hot_encoded_test = one_hot_encoder.transform(X_test[low_cardinality])
        one_hot_df_test = pd.DataFrame(one_hot_encoded_test, columns=one_hot_columns, index=X_test.index)
        X_test = pd.concat([X_test.drop(columns=low_cardinality), one_hot_df_test], axis=1)
except Exception as e:
    print(f"Error in one-hot encoding: {e}")

# Target encoding
try:
    target_encoder = TargetEncoder()
    if high_cardinality:
        X_train[high_cardinality] = target_encoder.fit_transform(X_train[high_cardinality], y_train)
        X_test[high_cardinality] = target_encoder.transform(X_test[high_cardinality])
except Exception as e:
    print(f"Error in target encoding: {e}")

print("\nEncoded Training Data Shape:", X_train.shape)
print("Encoded Test Data Shape:", X_test.shape)
print("\nTraining Data Columns:")
print(X_train.columns.tolist())

Error in one-hot encoding: OneHotEncoder.__init__() got an unexpected keyword argument 'sparse'

Encoded Training Data Shape: (126240, 54)
Encoded Test Data Shape: (31560, 54)

Training Data Columns:
['frame.time', 'ip.src_host', 'ip.dst_host', 'arp.dst.proto_ipv4', 'arp.opcode', 'arp.hw.size', 'arp.src.proto_ipv4', 'icmp.checksum', 'icmp.seq_le', 'icmp.transmit_timestamp', 'http.file_data', 'http.content_length', 'http.request.uri.query', 'http.request.method', 'http.referer', 'http.request.full_uri', 'http.request.version', 'http.response', 'tcp.ack', 'tcp.ack_raw', 'tcp.checksum', 'tcp.connection.fin', 'tcp.connection.rst', 'tcp.connection.syn', 'tcp.connection.synack', 'tcp.dstport', 'tcp.flags', 'tcp.flags.ack', 'tcp.len', 'tcp.options', 'tcp.payload', 'tcp.seq', 'tcp.srcport', 'udp.port', 'udp.stream', 'udp.time_delta', 'dns.qry.name', 'dns.qry.name.len', 'dns.qry.qu', 'dns.retransmission', 'dns.retransmit_request', 'mqtt.conack.flags', 'mqtt.conflag.cleansess', 'mqtt.conflags', 

In [ ]:
# Define low-cardinality features (from Step 2)
low_cardinality = [
    'arp.dst.proto_ipv4', 'arp.src.proto_ipv4', 'http.request.method', 'http.referer',
    'http.request.version', 'dns.qry.name.len', 'mqtt.conack.flags', 'mqtt.protoname',
    'mqtt.topic', 'arp.opcode', 'arp.hw.size', 'http.response', 'tcp.connection.fin',
    'tcp.connection.rst', 'tcp.connection.syn', 'tcp.connection.synack', 'tcp.flags',
    'tcp.flags.ack', 'dns.retransmission', 'dns.retransmit_request', 'mqtt.conflag.cleansess',
    'mqtt.conflags', 'mqtt.hdrflags', 'mqtt.len', 'mqtt.msgtype', 'mqtt.proto_len',
    'mqtt.topic_len', 'mqtt.ver'
]

# Inspect unique values
print("\nUnique Values for Low-Cardinality Features:")
for col in low_cardinality:
    unique_vals = df[col].unique()
    print(f"{col}: {len(unique_vals)} unique values - {unique_vals[:10]}")


Unique Values for Low-Cardinality Features:
arp.dst.proto_ipv4: 8 unique values - ['0.0' '0' '192.168.0.128' '192.168.0.170' '192.168.0.1' '192.168.0.101'
 '192.168.0.147' '192.168.0.129']
arp.src.proto_ipv4: 8 unique values - ['0.0' '0' '192.168.0.170' '192.168.0.128' '192.168.0.101' '192.168.0.1'
 '0.0.0.0' '192.168.0.129']
http.request.method: 6 unique values - ['0.0' '0' 'GET' 'POST' 'OPTIONS' 'TRACE']
http.referer: 4 unique values - ['0.0' '0'
 '() { _; } >_[$($())] { echo 93e4r0-CVE-2014-6278: true; echo;echo; }'
 '127.0.0.1']
http.request.version: 8 unique values - ['0' '0.0' 'HTTP/1.1' 'HTTP/1.0'
 'Src=javascript:alert(\'Vulnerable\')><Img Src=\\" HTTP/1.1'
 '/etc/passwd|?data=Download HTTP/1.1' '-a HTTP/1.1' 'By Dr HTTP/1.1']
dns.qry.name.len: 8 unique values - ['0.0' '1.0' '0' '0.debian.pool.ntp.org' '_googlecast._tcp.local'
 '1.debian.pool.ntp.org' '2.debian.pool.ntp.org' '3.debian.pool.ntp.org']
mqtt.conack.flags: 3 unique values - ['0.0' '0' '0x00000000']
mqtt.protoname: 

In [ ]:
from sklearn.preprocessing import OneHotEncoder
from category_encoders import TargetEncoder
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np

# Define features
low_cardinality = [
    'arp.dst.proto_ipv4', 'arp.src.proto_ipv4', 'http.request.method', 'http.referer',
    'http.request.version', 'dns.qry.name.len', 'mqtt.conack.flags', 'mqtt.protoname',
    'mqtt.topic', 'arp.opcode', 'arp.hw.size', 'http.response', 'tcp.connection.fin',
    'tcp.connection.rst', 'tcp.connection.syn', 'tcp.connection.synack', 'tcp.flags',
    'tcp.flags.ack', 'dns.retransmission', 'dns.retransmit_request', 'mqtt.conflag.cleansess',
    'mqtt.conflags', 'mqtt.hdrflags', 'mqtt.len', 'mqtt.msgtype', 'mqtt.proto_len',
    'mqtt.topic_len', 'mqtt.ver'
]
high_cardinality = [
    'frame.time', 'ip.src_host', 'ip.dst_host', 'http.file_data', 'http.request.uri.query',
    'http.request.full_uri', 'tcp.options', 'tcp.payload', 'tcp.srcport', 'mqtt.msg'
]
exclude_features = [
    'icmp.unused', 'http.tls_port', 'dns.qry.type', 'dns.retransmit_request_in',
    'mbtcp.len', 'mbtcp.trans_id', 'mbtcp.unit_id'
]

# Define features and target
target_col = 'Attack_label'
X = df.drop(columns=[target_col, 'Attack_type'] + exclude_features)
y = df[target_col]

# Convert low-cardinality features to string
for col in low_cardinality:
    X[col] = X[col].astype(str)

# Split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Debug: Check unique values in X_train
print("\nUnique Values in X_train for Low-Cardinality Features:")
for col in low_cardinality:
    unique_vals = X_train[col].unique()
    print(f"{col}: {len(unique_vals)} unique values - {unique_vals[:10]}")

# One-hot encoding
try:
    one_hot_encoder = OneHotEncoder(sparse_output=True, handle_unknown='ignore')  # Updated parameter
    if low_cardinality:
        one_hot_encoded = one_hot_encoder.fit_transform(X_train[low_cardinality])
        print(f"One-hot encoded shape: {one_hot_encoded.shape}")
        one_hot_columns = one_hot_encoder.get_feature_names_out(low_cardinality)
        # Convert sparse matrix to dense for DataFrame
        one_hot_df = pd.DataFrame.sparse.from_spmatrix(one_hot_encoded, columns=one_hot_columns, index=X_train.index)
        X_train = pd.concat([X_train.drop(columns=low_cardinality), one_hot_df], axis=1)

        # Apply to test data
        one_hot_encoded_test = one_hot_encoder.transform(X_test[low_cardinality])
        one_hot_df_test = pd.DataFrame.sparse.from_spmatrix(one_hot_encoded_test, columns=one_hot_columns, index=X_test.index)
        X_test = pd.concat([X_test.drop(columns=low_cardinality), one_hot_df_test], axis=1)
except Exception as e:
    print(f"Error in one-hot encoding: {e}")

# Target encoding
try:
    target_encoder = TargetEncoder()
    if high_cardinality:
        # Check high-cardinality features before encoding
        print("\nHigh-Cardinality Features Before Target Encoding:")
        for col in high_cardinality:
            print(f"{col}: {X_train[col].dtype}, Sample: {X_train[col].head().tolist()}")
        X_train[high_cardinality] = target_encoder.fit_transform(X_train[high_cardinality], y_train)
        X_test[high_cardinality] = target_encoder.transform(X_test[high_cardinality])
        # Check after encoding
        print("\nHigh-Cardinality Features After Target Encoding:")
        for col in high_cardinality:
            print(f"{col}: {X_train[col].dtype}, Sample: {X_train[col].head().tolist()}")
except Exception as e:
    print(f"Error in target encoding: {e}")

print("\nEncoded Training Data Shape:", X_train.shape)
print("Encoded Test Data Shape:", X_test.shape)
print("\nTraining Data Columns:")
print(X_train.columns.tolist())


Unique Values in X_train for Low-Cardinality Features:
arp.dst.proto_ipv4: 8 unique values - ['0' '0.0' '192.168.0.128' '192.168.0.170' '192.168.0.1' '192.168.0.147'
 '192.168.0.101' '192.168.0.129']
arp.src.proto_ipv4: 8 unique values - ['0' '0.0' '192.168.0.170' '192.168.0.128' '192.168.0.1' '0.0.0.0'
 '192.168.0.101' '192.168.0.129']
http.request.method: 6 unique values - ['0' 'GET' '0.0' 'POST' 'TRACE' 'OPTIONS']
http.referer: 4 unique values - ['0.0' '0' '127.0.0.1'
 '() { _; } >_[$($())] { echo 93e4r0-CVE-2014-6278: true; echo;echo; }']
http.request.version: 7 unique values - ['0' 'HTTP/1.1' 'HTTP/1.0' '0.0'
 'Src=javascript:alert(\'Vulnerable\')><Img Src=\\" HTTP/1.1'
 '/etc/passwd|?data=Download HTTP/1.1' '-a HTTP/1.1']
dns.qry.name.len: 7 unique values - ['0.0' '0' '1.0' '1.debian.pool.ntp.org' '0.debian.pool.ntp.org'
 '3.debian.pool.ntp.org' '2.debian.pool.ntp.org']
mqtt.conack.flags: 3 unique values - ['0.0' '0' '0x00000000']
mqtt.protoname: 3 unique values - ['0.0' '0' 'MQ

In [ ]:
# Check class distribution
print("\nClass Distribution of Attack_label:")
print(y_train.value_counts(normalize=True))
print("\nAbsolute Counts:")
print(y_train.value_counts())


Class Distribution of Attack_label:
Attack_label
1    0.84699
0    0.15301
Name: proportion, dtype: float64

Absolute Counts:
Attack_label
1    106924
0     19316
Name: count, dtype: int64


In [ ]:
from imblearn.over_sampling import SMOTE
import pandas as pd

# Apply SMOTE
try:
    smote = SMOTE(random_state=42)
    X_train_smote, y_train_smote = smote.fit_resample(X_train, y_train)

    print("\nClass Distribution After SMOTE:")
    print(pd.Series(y_train_smote).value_counts(normalize=True))
    print("\nAbsolute Counts After SMOTE:")
    print(pd.Series(y_train_smote).value_counts())

    print("\nSMOTE Training Data Shape:", X_train_smote.shape)
    print("SMOTE Test Data Shape (unchanged):", X_test.shape)
    print("\nSMOTE Training Data Columns:")
    print(X_train_smote.columns.tolist())
except Exception as e:
    print(f"Error in SMOTE: {e}")

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:921: UserWarning: pandas.DataFrame with sparse columns found.It will be converted to a dense numpy array.
  warnings.warn(



Class Distribution After SMOTE:
Attack_label
1    0.5
0    0.5
Name: proportion, dtype: float64

Absolute Counts After SMOTE:
Attack_label
1    106924
0    106924
Name: count, dtype: int64

SMOTE Training Data Shape: (213848, 130)
SMOTE Test Data Shape (unchanged): (31560, 130)

SMOTE Training Data Columns:
['frame.time', 'ip.src_host', 'ip.dst_host', 'icmp.checksum', 'icmp.seq_le', 'icmp.transmit_timestamp', 'http.file_data', 'http.content_length', 'http.request.uri.query', 'http.request.full_uri', 'tcp.ack', 'tcp.ack_raw', 'tcp.checksum', 'tcp.dstport', 'tcp.len', 'tcp.options', 'tcp.payload', 'tcp.seq', 'tcp.srcport', 'udp.port', 'udp.stream', 'udp.time_delta', 'dns.qry.name', 'dns.qry.qu', 'mqtt.msg_decoded_as', 'mqtt.msg', 'arp.dst.proto_ipv4_0', 'arp.dst.proto_ipv4_0.0', 'arp.dst.proto_ipv4_192.168.0.1', 'arp.dst.proto_ipv4_192.168.0.101', 'arp.dst.proto_ipv4_192.168.0.128', 'arp.dst.proto_ipv4_192.168.0.129', 'arp.dst.proto_ipv4_192.168.0.147', 'arp.dst.proto_ipv4_192.168.0.170

In [ ]:
print("\nClass Distribution of Attack_label:")
print(y_train.value_counts(normalize=True))
print("\nAbsolute Counts:")
print(y_train.value_counts())


Class Distribution of Attack_label:
Attack_label
1    0.84699
0    0.15301
Name: proportion, dtype: float64

Absolute Counts:
Attack_label
1    106924
0     19316
Name: count, dtype: int64


In [ ]:
!pip install imblearn

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
import pandas as pd
import numpy as np

# Define models
models = {
    'Random Forest': RandomForestClassifier(n_estimators=100, random_state=42),
    'Decision Tree': DecisionTreeClassifier(random_state=42),
    'KNN': KNeighborsClassifier(n_neighbors=5),
    'Logistic Regression': LogisticRegression(max_iter=1000, random_state=42),
    'XGBoost': XGBClassifier(use_label_encoder=False, eval_metric='logloss', random_state=42)
}

# Train and evaluate models
results = []
for name, model in models.items():
    try:
        # Train
        model.fit(X_train_smote, y_train_smote)
        # Predict
        y_pred = model.predict(X_test)
        # Metrics
        accuracy = accuracy_score(y_test, y_pred)
        precision = precision_score(y_test, y_pred)
        recall = recall_score(y_test, y_pred)
        f1 = f1_score(y_test, y_pred)
        cm = confusion_matrix(y_test, y_pred)
        tn, fp, fn, tp = cm.ravel()
        fpr = fp / (fp + tn) if (fp + tn) > 0 else 0
        fnr = fn / (fn + tp) if (fn + tp) > 0 else 0
        results.append({
            'Model': name,
            'Accuracy': accuracy,
            'Precision': precision,
            'Recall': recall,
            'F1-Score': f1,
            'FPR': fpr,
            'FNR': fnr
        })
        print(f"\nResults for {name}:")
        print(f"Accuracy: {accuracy:.4f}")
        print(f"Precision: {precision:.4f}")
        print(f"Recall: {recall:.4f}")
        print(f"F1-Score: {f1:.4f}")
        print(f"FPR: {fpr:.4f}")
        print(f"FNR: {fnr:.4f}")
        print(f"Confusion Matrix:\n{cm}")
    except Exception as e:
        print(f"Error training {name}: {e}")

# Define DNN
dnn_model = Sequential([
    Dense(128, activation='relu', input_shape=(X_train_smote.shape[1],)),
    Dropout(0.3),
    Dense(64, activation='relu'),
    Dropout(0.3),
    Dense(32, activation='relu'),
    Dense(1, activation='sigmoid')
])

# Compile DNN
dnn_model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train DNN
try:
    history = dnn_model.fit(
        X_train_smote, y_train_smote,
        epochs=20,
        batch_size=128,
        validation_split=0.2,
        verbose=1
    )
    # Predict
    y_pred_proba = dnn_model.predict(X_test)
    y_pred = (y_pred_proba > 0.5).astype(int).flatten()
    # Metrics
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    cm = confusion_matrix(y_test, y_pred)
    tn, fp, fn, tp = cm.ravel()
    fpr = fp / (fp + tn) if (fp + tn) > 0 else 0
    fnr = fn / (fn + tp) if (fn + tp) > 0 else 0
    results.append({
        'Model': 'DNN',
        'Accuracy': accuracy,
        'Precision': precision,
        'Recall': recall,
        'F1-Score': f1,
        'FPR': fpr,
        'FNR': fnr
    })
    print("\nResults for DNN:")
    print(f"Accuracy: {accuracy:.4f}")
    print(f"Precision: {precision:.4f}")
    print(f"Recall: {recall:.4f}")
    print(f"F1-Score: {f1:.4f}")
    print(f"FPR: {fpr:.4f}")
    print(f"FNR: {fnr:.4f}")
    print(f"Confusion Matrix:\n{cm}")
except Exception as e:
    print(f"Error training DNN: {e}")

# Summarize results
results_df = pd.DataFrame(results)
print("\nSummary of Results:")
print(results_df)

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:921: UserWarning: pandas.DataFrame with sparse columns found.It will be converted to a dense numpy array.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:921: UserWarning: pandas.DataFrame with sparse columns found.It will be converted to a dense numpy array.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:921: UserWarning: pandas.DataFrame with sparse columns found.It will be converted to a dense numpy array.
  warnings.warn(



Results for Random Forest:
Accuracy: 1.0000
Precision: 1.0000
Recall: 1.0000
F1-Score: 1.0000
FPR: 0.0000
FNR: 0.0000
Confusion Matrix:
[[ 4985     0]
 [    0 26575]]


/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:921: UserWarning: pandas.DataFrame with sparse columns found.It will be converted to a dense numpy array.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:921: UserWarning: pandas.DataFrame with sparse columns found.It will be converted to a dense numpy array.
  warnings.warn(



Results for Decision Tree:
Accuracy: 0.8420
Precision: 0.8420
Recall: 1.0000
F1-Score: 0.9143
FPR: 1.0000
FNR: 0.0000
Confusion Matrix:
[[    0  4985]
 [    0 26575]]


/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:921: UserWarning: pandas.DataFrame with sparse columns found.It will be converted to a dense numpy array.
  warnings.warn(



Results for KNN:
Accuracy: 0.8032
Precision: 0.9378
Recall: 0.8207
F1-Score: 0.8753
FPR: 0.2901
FNR: 0.1793
Confusion Matrix:
[[ 3539  1446]
 [ 4766 21809]]


/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:921: UserWarning: pandas.DataFrame with sparse columns found.It will be converted to a dense numpy array.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:921: UserWarning: pandas.DataFrame with sparse columns found.It will be converted to a dense numpy array.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:575: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")



Results for Logistic Regression:
Accuracy: 0.5849
Precision: 0.9864
Recall: 0.5141
F1-Score: 0.6760
FPR: 0.0377
FNR: 0.4859
Confusion Matrix:
[[ 4797   188]
 [12912 13663]]
Error training XGBoost: feature_names must be string, and may not contain [, ] or <


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/20
1337/1337 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.6145 - loss: 3005981.2500 - val_accuracy: 9.3524e-04 - val_loss: 1.6305
Epoch 2/20
1337/1337 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - accuracy: 0.6312 - loss: 1985.3290 - val_accuracy: 9.3524e-04 - val_loss: 1.7549
Epoch 3/20
1337/1337 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - accuracy: 0.6279 - loss: 581.3385 - val_accuracy: 0.0054 - val_loss: 1.8344
Epoch 4/20
1337/1337 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - accuracy: 0.6267 - loss: 166.5046 - val_accuracy: 0.0054 - val_loss: 1.6752
Epoch 5/20
1337/1337 ━━━━━━━━━━━━━━━━━━━━ 7s 5ms/step - accuracy: 0.6267 - loss: 75.7253 - val_accuracy: 0.0054 - val_loss: 1.6372
Epoch 6/20
1337/1337 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - accuracy: 0.6250 - loss: 161.2055 - val_accuracy: 0.0054 - val_loss: 0.9603
Epoch 7/20
1337/1337 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - accuracy: 0.6250 - loss: 45.0781 - val_accuracy: 0.0054 - val_loss: 0.8879
Epoch 8/20
1337/1337 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - accurac

In [ ]:
!pip install xgboost tensorflow

In [ ]:
print("\nClass Distribution of Attack_label:")
print(y_train.value_counts(normalize=True))
print("\nAbsolute Counts:")
print(y_train.value_counts())


Class Distribution of Attack_label:
Attack_label
1    0.84699
0    0.15301
Name: proportion, dtype: float64

Absolute Counts:
Attack_label
1    106924
0     19316
Name: count, dtype: int64


In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import cross_val_score
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Input
import pandas as pd
import numpy as np

# Sanitize column names
def sanitize_column_names(columns):
    invalid_chars = ['[', ']', '<', '>', '{', '}', '(', ')', ';', ':', '$']
    sanitized = []
    for col in columns:
        new_col = col
        for char in invalid_chars:
            new_col = new_col.replace(char, '_')
        sanitized.append(new_col)
    return sanitized

X_train_smote.columns = sanitize_column_names(X_train_smote.columns)
X_test.columns = sanitize_column_names(X_test.columns)

# Scale features for KNN, Logistic Regression, and DNN
scaler = StandardScaler()
X_train_smote_scaled = scaler.fit_transform(X_train_smote)
X_test_scaled = scaler.transform(X_test)
X_train_smote_scaled = pd.DataFrame(X_train_smote_scaled, columns=X_train_smote.columns)
X_test_scaled = pd.DataFrame(X_test_scaled, columns=X_test.columns)

# Define models
models = {
    'Random Forest': RandomForestClassifier(n_estimators=100, random_state=42),
    'Decision Tree': DecisionTreeClassifier(max_depth=10, random_state=42),  # Pruned
    'KNN': KNeighborsClassifier(n_neighbors=10),  # Tuned
    'Logistic Regression': LogisticRegression(max_iter=1000, random_state=42),
    'XGBoost': XGBClassifier(use_label_encoder=False, eval_metric='logloss', random_state=42)
}

# Train and evaluate models
results = []
for name, model in models.items():
    try:
        # Use scaled data for KNN and Logistic Regression
        X_train_model = X_train_smote_scaled if name in ['KNN', 'Logistic Regression'] else X_train_smote
        X_test_model = X_test_scaled if name in ['KNN', 'Logistic Regression'] else X_test

        # Train
        model.fit(X_train_model, y_train_smote)
        # Predict
        y_pred = model.predict(X_test_model)
        # Metrics
        accuracy = accuracy_score(y_test, y_pred)
        precision = precision_score(y_test, y_pred)
        recall = recall_score(y_test, y_pred)
        f1 = f1_score(y_test, y_pred)
        cm = confusion_matrix(y_test, y_pred)
        tn, fp, fn, tp = cm.ravel()
        fpr = fp / (fp + tn) if (fp + tn) > 0 else 0
        fnr = fn / (fn + tp) if (fn + tp) > 0 else 0
        results.append({
            'Model': name,
            'Accuracy': accuracy,
            'Precision': precision,
            'Recall': recall,
            'F1-Score': f1,
            'FPR': fpr,
            'FNR': fnr
        })
        print(f"\nResults for {name}:")
        print(f"Accuracy: {accuracy:.4f}")
        print(f"Precision: {precision:.4f}")
        print(f"Recall: {recall:.4f}")
        print(f"F1-Score: {f1:.4f}")
        print(f"FPR: {fpr:.4f}")
        print(f"FNR: {fnr:.4f}")
        print(f"Confusion Matrix:\n{cm}")

        # Random Forest: Feature importance and cross-validation
        if name == 'Random Forest':
            importances = pd.DataFrame({
                'Feature': X_train_smote.columns,
                'Importance': model.feature_importances_
            }).sort_values('Importance', ascending=False)
            print(f"\nTop 10 Feature Importances for {name}:")
            print(importances.head(10))
            cv_scores = cross_val_score(model, X_train_smote, y_train_smote, cv=5, scoring='accuracy')
            print(f"Cross-Validation Accuracy: {cv_scores.mean():.4f} ± {cv_scores.std():.4f}")
    except Exception as e:
        print(f"Error training {name}: {e}")

# Define DNN with Input layer
dnn_model = Sequential([
    Input(shape=(X_train_smote.shape[1],)),
    Dense(128, activation='relu'),
    Dropout(0.3),
    Dense(64, activation='relu'),
    Dropout(0.3),
    Dense(32, activation='relu'),
    Dense(1, activation='sigmoid')
])

# Compile DNN
dnn_model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train DNN on scaled data
try:
    history = dnn_model.fit(
        X_train_smote_scaled, y_train_smote,
        epochs=20,
        batch_size=128,
        validation_split=0.2,
        verbose=1
    )
    # Predict
    y_pred_proba = dnn_model.predict(X_test_scaled)
    y_pred = (y_pred_proba > 0.5).astype(int).flatten()
    # Metrics
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    cm = confusion_matrix(y_test, y_pred)
    tn, fp, fn, tp = cm.ravel()
    fpr = fp / (fp + tn) if (fp + tn) > 0 else 0
    fnr = fn / (fn + tp) if (fn + tp) > 0 else 0
    results.append({
        'Model': 'DNN',
        'Accuracy': accuracy,
        'Precision': precision,
        'Recall': recall,
        'F1-Score': f1,
        'FPR': fpr,
        'FNR': fnr
    })
    print("\nResults for DNN:")
    print(f"Accuracy: {accuracy:.4f}")
    print(f"Precision: {precision:.4f}")
    print(f"Recall: {recall:.4f}")
    print(f"F1-Score: {f1:.4f}")
    print(f"FPR: {fpr:.4f}")
    print(f"FNR: {fnr:.4f}")
    print(f"Confusion Matrix:\n{cm}")
except Exception as e:
    print(f"Error training DNN: {e}")

# Summarize results
results_df = pd.DataFrame(results)
print("\nSummary of Results:")
print(results_df)

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:921: UserWarning: pandas.DataFrame with sparse columns found.It will be converted to a dense numpy array.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:921: UserWarning: pandas.DataFrame with sparse columns found.It will be converted to a dense numpy array.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:921: UserWarning: pandas.DataFrame with sparse columns found.It will be converted to a dense numpy array.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:921: UserWarning: pandas.DataFrame with sparse columns found.It will be converted to a dense numpy array.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:921: UserWarning: pandas.DataFrame with sparse columns found.It will be converted to a dense numpy array.
  warnings.warn(



Results for Random Forest:
Accuracy: 1.0000
Precision: 1.0000
Recall: 1.0000
F1-Score: 1.0000
FPR: 0.0000
FNR: 0.0000
Confusion Matrix:
[[ 4985     0]
 [    0 26575]]

Top 10 Feature Importances for Random Forest:
                  Feature  Importance
0              frame.time    0.137989
73         mqtt.topic_0.0    0.127995
67  mqtt.conack.flags_0.0    0.123523
72           mqtt.topic_0    0.089280
70     mqtt.protoname_0.0    0.083043
60   dns.qry.name.len_0.0    0.074140
66    mqtt.conack.flags_0    0.059626
18            tcp.srcport    0.053701
59     dns.qry.name.len_0    0.037037
15            tcp.options    0.035235


/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:921: UserWarning: pandas.DataFrame with sparse columns found.It will be converted to a dense numpy array.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:921: UserWarning: pandas.DataFrame with sparse columns found.It will be converted to a dense numpy array.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:921: UserWarning: pandas.DataFrame with sparse columns found.It will be converted to a dense numpy array.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:921: UserWarning: pandas.DataFrame with sparse columns found.It will be converted to a dense numpy array.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:921: UserWarning: pandas.DataFrame with sparse columns found.It will be converted to a dense numpy array.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklea

Cross-Validation Accuracy: 1.0000 ± 0.0000


/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:921: UserWarning: pandas.DataFrame with sparse columns found.It will be converted to a dense numpy array.
  warnings.warn(



Results for Decision Tree:
Accuracy: 0.8420
Precision: 0.8420
Recall: 1.0000
F1-Score: 0.9143
FPR: 1.0000
FNR: 0.0000
Confusion Matrix:
[[    0  4985]
 [    0 26575]]

Results for KNN:
Accuracy: 0.9999
Precision: 0.9999
Recall: 1.0000
F1-Score: 1.0000
FPR: 0.0004
FNR: 0.0000
Confusion Matrix:
[[ 4983     2]
 [    0 26575]]

Results for Logistic Regression:
Accuracy: 1.0000
Precision: 1.0000
Recall: 1.0000
F1-Score: 1.0000
FPR: 0.0000
FNR: 0.0000
Confusion Matrix:
[[ 4985     0]
 [    0 26575]]


/usr/local/lib/python3.11/dist-packages/xgboost/data.py:575: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")
/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [19:18:42] WARNING: /workspace/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
/usr/local/lib/python3.11/dist-packages/xgboost/data.py:575: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")



Results for XGBoost:
Accuracy: 0.1748
Precision: 1.0000
Recall: 0.0200
F1-Score: 0.0393
FPR: 0.0000
FNR: 0.9800
Confusion Matrix:
[[ 4985     0]
 [26043   532]]
Epoch 1/20
1337/1337 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - accuracy: 0.9871 - loss: 0.0333 - val_accuracy: 1.0000 - val_loss: 5.3031e-06
Epoch 2/20
1337/1337 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - accuracy: 0.9999 - loss: 4.6726e-04 - val_accuracy: 1.0000 - val_loss: 7.4726e-06
Epoch 3/20
1337/1337 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 1.0000 - loss: 6.7447e-04 - val_accuracy: 1.0000 - val_loss: 3.3057e-09
Epoch 4/20
1337/1337 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - accuracy: 1.0000 - loss: 2.1847e-04 - val_accuracy: 1.0000 - val_loss: 3.5686e-10
Epoch 5/20
1337/1337 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - accuracy: 1.0000 - loss: 8.9104e-05 - val_accuracy: 1.0000 - val_loss: 6.0121e-12
Epoch 6/20
1337/1337 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 1.0000 - loss: 2.5411e-04 - val_accuracy: 1.0000 - val_loss: 8.5877e-13
Epoch 7/20
1

In [ ]:
print(OneHotEncoder.__module__)

sklearn.preprocessing._encoders


1.6.1


KeyError: "['mqtt.conackAdams', 'mqtt.metres', 'mqtt.config.cleans', 'mqtt.config'] not in index"